/** @type {import('@bacons/apple-targets/app.plugin').Config} */
// The ONE shared WidgetKit extension target for every widget-family feature
// (home-screen widgets, ActivityKit Live Activities, iOS 18 Control Center
// controls). iOS allows a single widget extension per app, so new features
// register themselves in PegadaWidgetsBundle.swift instead of adding another
// target. Keep this file byte-identical across feature branches so merges
// resolve cleanly.
//
// deploymentTarget 16.2 is the floor for the ActivityKit content APIs the
// Live Activity uses; newer-OS features (iOS 17 widget APIs, iOS 18
// controls) gate themselves with @available / #available in their own Swift
// files. Team ID comes from EAS credentials at release build time; local
// simulator builds don't sign.
module.exports = {
  type: "widget",
  name: "PegadaWidgets",
  displayName: "Pegada",
  // `.` prefix appends to the main app's bundle id -> app.pegada.widgets
  bundleIdentifier: ".widgets",
  deploymentTarget: "16.2",
  frameworks: ["SwiftUI", "WidgetKit", "ActivityKit", "AppIntents"],
  // Design tokens mirrored 1:1 from packages/shared/themes/themes.ts (light /
  // dark); prebuild converts them to colorsets. NOTE: the plugin expects
  // `{ light, dark }` (not `{ color, darkColor }`) - anything else silently
  // writes an EMPTY colorset.
  //
  // COLOR SPACE WARNING: @bacons/apple-targets (see
  // node_modules/@bacons/apple-targets/build/colorset/with-ios-colorset.js,
  // `createColor`) always tags the emitted Contents.json as
  // "color-space": "display-p3", but it gets there by parsing the CSS string
  // below as plain sRGB (via @react-native/normalize-colors) and writing
  // those 0-1 components verbatim - it never actually converts anything to
  // P3. Rendered on a wide-gamut display, a P3-tagged sRGB numeral reads
  // MORE saturated than the real sRGB color (confirmed: BrandPink measured
  // ~#FF55A3 instead of the intended #EF62A1). The plugin has no
  // color-space option, and prebuild rewrites every colorset's Contents.json
  // unconditionally on every run (unconditional `writeFile`, no merge/skip),
  // so committing hand-fixed Contents.json files would just get clobbered
  // on the next prebuild.
  //
  // Fix: instead of feeding the plugin the theme's literal sRGB color, feed
  // it the sRGB->Display-P3 gamut-mapped equivalent (as an rgb() string, so
  // normalize-colors parses it as literal 0-255 components instead of
  // reinterpreting hsl() through its own sRGB math). The plugin then writes
  // those P3-mapped numbers into a "display-p3" colorset, and a P3 display
  // renders them back to the ORIGINAL sRGB appearance. Conversion: sRGB ->
  // linear sRGB -> CIE XYZ (D65) -> linear Display P3 -> gamma-encoded
  // Display P3, using the standard IEC 61966-2-1 / SMPTE RP 431-2 matrices.
  // Values below are generated by `node scripts/srgb-to-p3-widget-colors.js`
  // - re-run it and paste the output here if these theme colors ever
  // change; do NOT hand-edit the rgb() values without it.
  colors: {
    $accent: "rgb(222, 107, 160)", // colors.primary (light) hsl(333, 81%, 66%) -> P3-mapped
    $widgetBackground: { light: "rgb(255, 255, 255)", dark: "rgb(0, 0, 0)" }, // colors.background (white/black are gamut-invariant)
    BrandPink: { light: "rgb(222, 107, 160)", dark: "rgb(196, 97, 143)" }, // colors.primary hsl(333, 81%, 66%) / hsl(333, 58%, 59%) -> P3-mapped
    PrimaryText: { light: "rgb(3, 8, 22)", dark: "rgb(242, 242, 242)" }, // colors.text hsl(222.2, 84%, 4.9%) / hsl(0, 0%, 95%) -> P3-mapped
    SubtitleText: { light: "rgb(91, 95, 108)", dark: "rgb(153, 153, 153)" }, // colors.subtitle hsl(222.2, 10%, 39%) / hsl(0, 0%, 60%) -> P3-mapped
    CardSurface: { light: "rgb(249, 249, 249)", dark: "rgb(38, 38, 38)" }, // colors.card hsl(0, 0%, 97.5%) / hsl(0, 0%, 15%) -> P3-mapped
    BorderSubtle: { light: "rgb(227, 232, 239)", dark: "rgb(31, 31, 31)" }, // colors.border hsl(214.3, 31.8%, 91.4%) / hsl(0, 0%, 12%) -> P3-mapped
  },
  // App Groups shared with the main app; harmless for entries that don't
  // read the shared container.
  entitlements: {
    "com.apple.security.application-groups": ["group.app.pegada"],
  },
};
