// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/delete-account" | "/[locale]/dog/[id]" | "/[locale]/privacy-policy" | "/[locale]/terms-of-use"
type AppRouteHandlerRoutes = "/api/queues/check-push-receipts" | "/api/queues/mail" | "/api/queues/process-image" | "/api/queues/send-push" | "/api/trpc/[trpc]" | "/api/webhooks/revenuecat" | "/store"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/delete-account": { "locale": string; }
  "/[locale]/dog/[id]": { "locale": string; "id": string; }
  "/[locale]/privacy-policy": { "locale": string; }
  "/[locale]/terms-of-use": { "locale": string; }
  "/api/queues/check-push-receipts": {}
  "/api/queues/mail": {}
  "/api/queues/process-image": {}
  "/api/queues/send-push": {}
  "/api/trpc/[trpc]": { "trpc": string; }
  "/api/webhooks/revenuecat": {}
  "/store": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
