version: "3.1"

name: "pegada-dev-environment"

services:
  postgres:
    container_name: pegada-postgres
    image: postgis/postgis
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: tony
      POSTGRES_PASSWORD: hawk
      POSTGRES_DB: pegada
    ports:
      - "3356:5432"

  redis:
    container_name: pegada-redis
    image: redis:alpine
    command: redis-server
    restart: always
    ports:
      - "6379:6379"

  redis-serverless:
    container_name: pegada-redis-serverless
    image: hiett/serverless-redis-http:latest
    restart: always
    ports:
      - "8079:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379"
