import AppIntents
import UIKit

// App Intents for Siri, Shortcuts and Spotlight. This file is compiled into
// the MAIN app target (not an extension) by plugins/withAppIntents.js during
// `expo prebuild` -- App Shortcuts phrases only register from the app bundle.
//
// The intents deep-link through the pegada:// scheme, which expo-router
// resolves to the matching route (see src/app/(app)/(tabs)/*). Titles and
// descriptions are localized through the app's native strings mechanism:
// `ios["Localizable.strings"]` in packages/shared/i18n/locales/*/native.json,
// which Expo's locales support turns into <lang>.lproj/Localizable.strings.
// Siri phrases live in AppShortcuts.strings (generated by the same plugin
// from plugins/appIntents/appShortcutsPhrases.json).
//
// The app deploys to iOS 15.1, AppIntents needs 16.0, and the AppShortcut
// initializer with shortTitle/systemImageName needs 16.4 -- hence the gates.
// On anything older the intents simply don't register; nothing else changes.

/// Opens the app on the given deep-link path. These intents run inside the
/// main app process (openAppWhenRun foregrounds the app first), so routing
/// goes through UIApplication -> RCTLinkingManager -> expo-router.
@MainActor
private func openDeepLink(path: String) {
  guard let url = URL(string: "pegada://\(path)") else { return }
  UIApplication.shared.open(url, options: [:], completionHandler: nil)
}

// NOTE: identifier-style keys (not English text) because Expo's
// writeStringsFile emits .strings keys unquoted -- keys with spaces would
// produce invalid .strings syntax and fail the CopyStringsFile build step.
// `defaultValue` keeps a readable English fallback if a lookup ever misses.

@available(iOS 16.0, *)
struct StartSwipingIntent: AppIntent {
  static let title = LocalizedStringResource(
    "appIntents_startSwiping_title", defaultValue: "Start Swiping")
  static let description = IntentDescription(
    LocalizedStringResource(
      "appIntents_startSwiping_description",
      defaultValue: "Opens Pegada ready to meet new dogs."))
  static let openAppWhenRun: Bool = true

  @MainActor
  func perform() async throws -> some IntentResult {
    openDeepLink(path: "swipe")
    return .result()
  }
}

@available(iOS 16.0, *)
struct OpenMatchesIntent: AppIntent {
  static let title = LocalizedStringResource(
    "appIntents_openMatches_title", defaultValue: "Open Matches")
  static let description = IntentDescription(
    LocalizedStringResource(
      "appIntents_openMatches_description",
      defaultValue: "Opens your matches and conversations."))
  static let openAppWhenRun: Bool = true

  @MainActor
  func perform() async throws -> some IntentResult {
    openDeepLink(path: "messages")
    return .result()
  }
}

@available(iOS 16.4, *)
struct PegadaAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: StartSwipingIntent(),
      phrases: [
        "Start swiping in \(.applicationName)",
        "Find dogs in \(.applicationName)",
      ],
      shortTitle: LocalizedStringResource(
        "appIntents_startSwiping_title", defaultValue: "Start Swiping"),
      systemImageName: "pawprint.fill"
    )
    AppShortcut(
      intent: OpenMatchesIntent(),
      phrases: [
        "Open my matches in \(.applicationName)",
        "Show my \(.applicationName) matches",
      ],
      shortTitle: LocalizedStringResource(
        "appIntents_openMatches_title", defaultValue: "Open Matches"),
      systemImageName: "heart.fill"
    )
  }
}
