import AppIntents
import UIKit

// App Intents for Siri, Shortcuts and Spotlight. This file is compiled into
// the MAIN app target (not an extension) by plugins/withAppIntents.js during
// `expo prebuild` -- App Shortcuts phrases only register from the app bundle.
//
// The intents deep-link through the pegada:// scheme, which expo-router
// resolves to the matching route (see src/app/(app)/(tabs)/*). Titles and
// descriptions are localized through the app's native strings mechanism:
// `ios["Localizable.strings"]` in packages/shared/i18n/locales/*/native.json,
// which Expo's locales support turns into <lang>.lproj/Localizable.strings.
// Siri phrases live in AppShortcuts.strings (generated by the same plugin
// from plugins/appIntents/appShortcutsPhrases.json).
//
// The app deploys to iOS 15.1, AppIntents needs 16.0, and the AppShortcut
// initializer with shortTitle/systemImageName needs 16.4 -- hence the gates.
// On anything older the intents simply don't register; nothing else changes.

/// Opens the app on the given deep-link path. These intents run inside the
/// main app process (openAppWhenRun foregrounds the app first), so routing
/// goes through UIApplication -> RCTLinkingManager -> expo-router.
private enum DeepLinkOpenError: Error {
  case invalidPath(String)
  case rejected(URL)
}

@MainActor
private func openDeepLink(path: String) async throws {
  guard let url = URL(string: "pegada://\(path)") else {
    throw DeepLinkOpenError.invalidPath(path)
  }

  guard await UIApplication.shared.open(url) else {
    throw DeepLinkOpenError.rejected(url)
  }
}

// NOTE: identifier-style keys (not English text) because Expo's
// writeStringsFile emits .strings keys unquoted -- keys with spaces would
// produce invalid .strings syntax and fail the CopyStringsFile build step.
// `defaultValue` keeps a readable English fallback if a lookup ever misses.

@available(iOS 16.0, *)
struct FindDogsIntent: AppIntent {
  static let title = LocalizedStringResource(
    "appIntents_findDogs_title", defaultValue: "Find dogs")
  static let description = IntentDescription(
    LocalizedStringResource(
      "appIntents_findDogs_description",
      defaultValue: "Opens Pegada to find new dogs."))
  // `supportedModes` replaces `openAppWhenRun` on iOS 26. Keep the legacy
  // property for iOS 16-25, where IntentModes is unavailable.
  static let openAppWhenRun: Bool = true
  @available(iOS 26.0, *)
  static let supportedModes: IntentModes = .foreground

  @MainActor
  func perform() async throws -> some IntentResult {
    try await openDeepLink(path: "swipe")
    return .result()
  }
}

@available(iOS 16.0, *)
struct OpenMatchesIntent: AppIntent {
  static let title = LocalizedStringResource(
    "appIntents_openMatches_title", defaultValue: "Open matches")
  static let description = IntentDescription(
    LocalizedStringResource(
      "appIntents_openMatches_description",
      defaultValue: "Opens your matches and conversations."))
  // `supportedModes` replaces `openAppWhenRun` on iOS 26. Keep the legacy
  // property for iOS 16-25, where IntentModes is unavailable.
  static let openAppWhenRun: Bool = true
  @available(iOS 26.0, *)
  static let supportedModes: IntentModes = .foreground

  @MainActor
  func perform() async throws -> some IntentResult {
    try await openDeepLink(path: "messages")
    return .result()
  }
}

@available(iOS 16.4, *)
struct PegadaAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: FindDogsIntent(),
      phrases: [
        "Find dogs in \(.applicationName)",
        "Show dogs in \(.applicationName)",
      ],
      shortTitle: LocalizedStringResource(
        "appIntents_findDogs_title", defaultValue: "Find dogs"),
      systemImageName: "pawprint.fill"
    )
    AppShortcut(
      intent: OpenMatchesIntent(),
      phrases: [
        "Open my matches in \(.applicationName)",
        "Show my matches in \(.applicationName)",
      ],
      shortTitle: LocalizedStringResource(
        "appIntents_openMatches_title", defaultValue: "Open matches"),
      systemImageName: "heart.fill"
    )
  }
}
