// @ts-nocheck
/**
 * Expo config plugin: applies the user's in-app theme choice to the iOS
 * window BEFORE the splash screen renders.
 *
 * Why this is needed:
 *   The app lets users force light/dark independently of the system
 *   appearance. That choice lives in AsyncStorage and is applied at JS
 *   runtime via Appearance.setColorScheme — which means on every cold start
 *   the native splash screen (and the window behind it) still follows the
 *   SYSTEM appearance until the JS bundle loads and reads storage. A user
 *   who forced dark mode on a light-mode device boots into a white splash
 *   that then flips to dark: the "splash blink".
 *
 *   The JS side mirrors the choice into NSUserDefaults via React Native's
 *   `Settings` API (key: `pegadaThemeOverride`, see
 *   src/contexts/ThemeProvider.tsx). This plugin injects a snippet into
 *   AppDelegate.swift, right after the UIWindow is created and before
 *   startReactNative shows the splash, that reads the key and sets
 *   `overrideUserInterfaceStyle` accordingly. The splash storyboard's
 *   background color asset already has a dark variant (generated by expo
 *   prebuild from ios.splash.dark), so overriding the window's style is
 *   enough for the splash — and everything after it — to resolve the right
 *   colors from the first frame. It also makes React Native's Appearance
 *   module report the forced scheme immediately, so the first JS render is
 *   already themed correctly.
 *
 *   Values "dark" and "light" force the style; "system" (or no key, e.g.
 *   fresh installs and users who never forced a theme) leaves the window
 *   following the system appearance — exactly today's behavior.
 */
const { withAppDelegate } = require("expo/config-plugins");
const { mergeContents } = require("@expo/config-plugins/build/utils/generateCode");

const OVERRIDE_SNIPPET = `    if let themeOverride = UserDefaults.standard.string(forKey: "pegadaThemeOverride"),
      themeOverride == "dark" || themeOverride == "light" {
      window?.overrideUserInterfaceStyle = themeOverride == "dark" ? .dark : .light
    }`;

const withInitialThemeOverride = (config) => {
  return withAppDelegate(config, (modConfig) => {
    if (modConfig.modResults.language !== "swift") {
      throw new Error(
        "withInitialThemeOverride: expected a Swift AppDelegate, found " +
          modConfig.modResults.language,
      );
    }

    modConfig.modResults.contents = mergeContents({
      tag: "initial-theme-override",
      src: modConfig.modResults.contents,
      newSrc: OVERRIDE_SNIPPET,
      anchor: /window = UIWindow\(frame: UIScreen\.main\.bounds\)/,
      offset: 1,
      comment: "//",
    }).contents;

    return modConfig;
  });
};

module.exports = withInitialThemeOverride;
